UPDATE USAGE_ATTRIBUTE SET ATTRIBUTE_NAME = 'SupplierName' WHERE ATTRIBUTE_NAME = 'ManufacturerName' AND ATTRIBUTE_VALUE = 'AKZO NOBEL';
UPDATE USAGE_ATTRIBUTE SET ATTRIBUTE_NAME = 'SupplierName' WHERE ATTRIBUTE_NAME = 'ManufacturerName' AND ATTRIBUTE_VALUE = 'Color Focus - FleetName';
UPDATE USAGE_ATTRIBUTE SET ATTRIBUTE_NAME = 'SupplierName' WHERE ATTRIBUTE_NAME = 'ManufacturerName' AND ATTRIBUTE_VALUE = 'Color Planner - FleetName';
UPDATE USAGE_ATTRIBUTE SET ATTRIBUTE_NAME = 'SupplierName' WHERE ATTRIBUTE_NAME = 'ManufacturerName' AND ATTRIBUTE_VALUE = 'FEDERAL STANDARD';
UPDATE USAGE_ATTRIBUTE SET ATTRIBUTE_NAME = 'SupplierName' WHERE ATTRIBUTE_NAME = 'ManufacturerName' AND ATTRIBUTE_VALUE = 'Federal Standard';
UPDATE USAGE_ATTRIBUTE SET ATTRIBUTE_NAME = 'SupplierName' WHERE ATTRIBUTE_NAME = 'ManufacturerName' AND ATTRIBUTE_VALUE = 'Light Industrial Coating - FleetName';
UPDATE USAGE_ATTRIBUTE SET ATTRIBUTE_NAME = 'SupplierName' WHERE ATTRIBUTE_NAME = 'ManufacturerName' AND ATTRIBUTE_VALUE = 'Pantone PMS Fleet - FleetName';
UPDATE USAGE_ATTRIBUTE SET ATTRIBUTE_NAME = 'SupplierName' WHERE ATTRIBUTE_NAME = 'ManufacturerName' AND ATTRIBUTE_VALUE = 'Prospector';
UPDATE USAGE_ATTRIBUTE SET ATTRIBUTE_NAME = 'SupplierName' WHERE ATTRIBUTE_NAME = 'ManufacturerName' AND ATTRIBUTE_VALUE = 'RAL';
UPDATE USAGE_ATTRIBUTE SET ATTRIBUTE_NAME = 'SupplierName' WHERE ATTRIBUTE_NAME = 'ManufacturerName' AND ATTRIBUTE_VALUE = 'Sherwin-Williams-Aerospace Coatings';
UPDATE USAGE_ATTRIBUTE SET ATTRIBUTE_NAME = 'SupplierName' WHERE ATTRIBUTE_NAME = 'ManufacturerName' AND ATTRIBUTE_VALUE = 'Spectramaster';
UPDATE USAGE_ATTRIBUTE SET ATTRIBUTE_NAME = 'SupplierName' WHERE ATTRIBUTE_NAME = 'ManufacturerName' AND ATTRIBUTE_VALUE = 'Spurlock Paint';
UPDATE USAGE_ATTRIBUTE SET ATTRIBUTE_NAME = 'SupplierName' WHERE ATTRIBUTE_NAME = 'ManufacturerName' AND ATTRIBUTE_VALUE = 'Standard Colors - FleetName';
UPDATE USAGE_ATTRIBUTE SET ATTRIBUTE_NAME = 'SupplierName' WHERE ATTRIBUTE_NAME = 'ManufacturerName' AND ATTRIBUTE_VALUE = 'Universal Colors';

UPDATE USAGE_ATTRIBUTE SET ATTRIBUTE_VALUE = REPLACE(ATTRIBUTE_VALUE, ' - FleetName', '') WHERE ATTRIBUTE_NAME = 'SupplierName' AND ATTRIBUTE_VALUE LIKE '% - FleetName%';
