UPDATE USAGE_ATTRIBUTE SET ATTRIBUTE_VALUE = REPLACE(ATTRIBUTE_VALUE, ' - FleetName', '') WHERE ATTRIBUTE_VALUE LIKE '% - FleetName%';
UPDATE USAGE_ATTRIBUTE SET ATTRIBUTE_VALUE = REPLACE(ATTRIBUTE_VALUE, ' - ManufacturerName', '') WHERE ATTRIBUTE_VALUE LIKE '% - ManufacturerName%';
UPDATE USAGE_ATTRIBUTE SET ATTRIBUTE_VALUE = REPLACE(ATTRIBUTE_VALUE, ' - MfgName', '') WHERE ATTRIBUTE_VALUE LIKE '% - MfgName%';
UPDATE USAGE_ATTRIBUTE SET ATTRIBUTE_VALUE = REPLACE(ATTRIBUTE_VALUE, ' - SupplierName', '') WHERE ATTRIBUTE_VALUE LIKE '% - SupplierName%';

UPDATE USAGE_ATTRIBUTE SET ATTRIBUTE_NAME = 'Federal Standard' WHERE ATTRIBUTE_VALUE='FEDERAL STANDARD' AND ATTRIBUTE_NAME = 'SupplierName';

UPDATE USAGE_ATTRIBUTE SET ATTRIBUTE_NAME = 'Aspen Trailer' WHERE ATTRIBUTE_VALUE='ASPEN TRAILER' AND ATTRIBUTE_NAME = 'ManufacturerName';
UPDATE USAGE_ATTRIBUTE SET ATTRIBUTE_NAME = 'Coachmen RV' WHERE ATTRIBUTE_VALUE='Coachmen Industries' AND ATTRIBUTE_NAME = 'ManufacturerName';
UPDATE USAGE_ATTRIBUTE SET ATTRIBUTE_NAME = 'Dodge Fleet' WHERE ATTRIBUTE_VALUE='Dodge Truck Fleet' AND ATTRIBUTE_NAME = 'ManufacturerName';
UPDATE USAGE_ATTRIBUTE SET ATTRIBUTE_NAME = 'Navistar IC Bus' WHERE ATTRIBUTE_VALUE='Navistar International Bus' AND ATTRIBUTE_NAME = 'ManufacturerName';
UPDATE USAGE_ATTRIBUTE SET ATTRIBUTE_NAME = 'Superior Finishes' WHERE ATTRIBUTE_VALUE='Superior Finish' AND ATTRIBUTE_NAME = 'ManufacturerName';
UPDATE USAGE_ATTRIBUTE SET ATTRIBUTE_NAME = 'Super City Manufacturing' WHERE ATTRIBUTE_VALUE='Super City' AND ATTRIBUTE_NAME = 'ManufacturerName';
